sudo: required
language: python
python:
  - "2.7"
# command to install package
before_install:
  - ./install.sh
  - pip install setuptools --upgrade
  - pip install -r requirements.txt
install:
  - python setup.py install
# command to run tests
script:
  - python tests/test.py
notifications:
  email: true
