sudo: required
language: python
python:
  - "2.7"
  - "2.7_with_system_site_packages"	# for PyQt
# command to install package
before_install:
  - pip install setuptools --upgrade
  - pip install -r requirements.txt
install:
  - sudo apt-get -qq install libfreetype6-dev liblcms2-dev libwebp-dev python-qt4
  - python setup.py install
# command to run tests
script:
  - python tests/test.py
notifications:
  email: true
